---
title: "525 hw 6"
output: pdf_document
date: "2023-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1(a)
```{r}
data=read.csv("/Users/liangdameinv/Desktop/525/azdiabetes.csv")
nu0 = 2 
sigma0_square=1
S=1000
formula=data$glu~data$npreg+data$bp+data$bmi+data$skin+data$ped+data$age
x = as.matrix(cbind(data[,1], data[,3:7]))
y = data$glu
n = length(y)
g=n
n=dim (x) [1] 
p=dim (x) [2]
Hg = (g/(g+1))*x%*%solve(t(x)%*%x)%*%t(x)
SSRg=t(y)%*%(diag (1 , nrow=n ) -Hg )%*%y
s2=1/rgamma (S,(nu0+n) / 2 , ( nu0*sigma0_square+SSRg) / 2 )
Vb= g*solve (t(x)%*%x) / (g+1)
Eb= Vb%*%t (x)%*%y
E=matrix (rnorm ( S*p , 0 , sqrt(s2)) , S , p )
beta=t(t(E%*%chol(Vb)) +c(Eb))
cat("posterior confidence intervals of npreg's beta",quantile(beta[,1],pro=c(0.25,0.75)),"\n")
cat("posterior confidence intervals of bp's beta",quantile(beta[,2],pro=c(0.25,0.75)),"\n")
cat("posterior confidence intervals of skin's beta",quantile(beta[,3],pro=c(0.25,0.75)),"\n")
cat("posterior confidence intervals of bmi's beta",quantile(beta[,4],pro=c(0.25,0.75)),"\n")
cat("posterior confidence intervals of ped's beta",quantile(beta[,5],pro=c(0.25,0.75)),"\n")
cat("posterior confidence intervals of age's beta",quantile(beta[,6],pro=c(0.25,0.75)))
```
## Problem 1(b)
```{r}
library(BAS)
glu.bic = bas.lm(y ~ npreg + bp + skin +bmi+ ped +age,
data = data, n.models = 2^6, prior = "BIC",
modelprior = beta.binomial(1, 1),
initprobs = "eplogp", pivot = FALSE
)
glu.mcmc = bas.lm(y ~ npreg + bp + skin +bmi+ ped +age,
data = data,
method = "MCMC",
MCMC.iterations = 20000, prior = "BIC",
modelprior = beta.binomial(1, 1),initprobs = "eplogp", pivot = FALSE
)
confint(coef(glu.mcmc))
cat(" the probablity of betaj does not equal to 0 is:",glu.mcmc$probne0)
criti=predict(glu.mcmc,newdata=data,estimator="BPM", se.fit=TRUE)
error_b=sum(criti$se.pred)
error_a=sum(x%*%t(beta)-y)
error_a-error_b<0
```
#According to the 2 model's prediction standard error, model in (a) has better result.


## Problem 2(c)
```{r}
require(LearnBayes)
library(MCMCpack)
library(mvtnorm)
data=read.csv("/Users/liangdameinv/Desktop/525/msparrownest.csv")
y=data$X0
x=data$X13.03
n=length(y)
p=2
pmn.beta=c( 0,0) 
psd.beta=c(10,100)
var.prop=var (log(y+1/2))*solve(t(x)%*%x)
beta.prop=matrix(c(var.prop,0,0,var.prop),nrow=2,ncol=2)
S=10000
beta=t(matrix(rep ( 0 , p ) ))
acs=0
BETA=matrix (0 , nrow=S , ncol=p )
set.seed ( 1 )
for(s in 1 : S )
{
beta.p= rmvnorm (1,beta,beta.prop)
lhr= sum(dpois(y , exp (x%*%beta.p ) , log=T) ) -sum (dpois(y, exp(x%*%beta ) , log=T)) +
sum (dnorm ( beta.p , pmn.beta , psd.beta , log=T) ) -
sum ( dnorm ( beta , pmn.beta , psd.beta , log=T) )
if ( log (runif (1)) < lhr ) { beta=beta.p ; acs=acs+1 }
BETA[s ,]=beta
}
cat("the posterior mean of alpha is:",mean(BETA[,1]),"\n")
cat("the posterior mean of beta is:",mean(BETA[,2]),"\n")
cat("the acceptance rate is:",acs/10000)
```

## Problem 2(d)
```{r}
data=read.csv("/Users/liangdameinv/Desktop/525/msparrownest.csv")
library(ggplot2)
# Create a data frame with the samples
posterior_data <- data.frame(alpha = BETA[,1], beta = BETA[,2])
prior_alpha_distribution <- na.omit(rnorm(20000, mean = 0, sd = 1))
prior_beta_distribution <- na.omit(rnorm(10000, mean = 0, sd = 1))
prior_data=data.frame(alpha = prior_alpha_distribution, beta = prior_beta_distribution)

plot(density(posterior_data$alpha),col="blue",main="plot of alpha's posterior distribution density")
plot(density(prior_data$alpha),col="red",main="plot of alpha's prior distribution density")

plot(density(posterior_data$beta),col="blue",main="plot of beta's posterior distribution density")
plot(density(prior_data$beta),col="red",main="plot of beta's prior distribution density")
# Create density plots for alpha
ggplot(posterior_data, aes(x = alpha)) +
  geom_density(color = "blue", alpha = 2, size = 1) +
  geom_density(data =prior_data,aes(x=alpha), color = "red", alpha = 2, size = 1) +
  labs(title = "Posterior vs. Prior Density for Alpha") +
  theme_minimal()

# Create density plots for beta
ggplot(posterior_data, aes(x = beta)) +
  geom_density(color = "blue", alpha = 2, size = 1) +
  geom_density(data =prior_data,aes(x=beta), color = "red", alpha = 2, size = 1) +
  labs(title = "Posterior vs. Prior Density for beta") +
  theme_minimal()
```

## Problem 2(e)
```{r}
data=read.csv("/Users/liangdameinv/Desktop/525/msparrownest.csv")
x_values <- seq(min(x), max(x), length.out = 100)
f_alpha_beta_samples <- matrix(NA, nrow = length(x_values), ncol = length(BETA[,1]))

for (i in 1:length(BETA[,1])) {
  alpha_sample <- BETA[,1][i]
  beta_sample <- BETA[,2][i]
  f_alpha_beta_samples[, i] <- exp(alpha_sample + beta_sample * x_values) / (1 + exp(alpha_sample + beta_sample * x_values))
}

quantiles <- apply(f_alpha_beta_samples, 1, function(x) quantile(x, c(0.025, 0.975)))

# Create a plot of the confidence band
plot(x_values, quantiles[1, ], type = "l", col = "blue", lwd = 2, xlab = "Wingspan (x)", ylab = expression(f[alpha*beta](x)), ylim = c(0, 1))
lines(x_values, quantiles[2, ], col = "blue", lwd = 2)
title("Confidence Band for f(alpha, beta)(x)")


```
